name: 'Container Image Cleanup'
description: 'Clean up old container images from a container registry based on tag patterns and retention policies'
branding:
  icon: 'trash-2'
  color: 'red'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install dependencies
      shell: bash
      run: pip install ${{ github.action_path }}

    - name: Run cleanup script
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPO_OWNER: ${{ github.repository_owner }}
      run: python -m container_registry_cleanup
