name: Release Please

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      contents: write # Required to create releases and tags.
      pull-requests: write # Required to open and update release PRs.
    steps:
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4
        id: release
